apiVersion: v1
kind: Namespace
metadata:
  name: web
---
apiVersion: v1
kind: Namespace
metadata:
  name: api
  labels:
    azure-key-vault-env-injection: enabled
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: sql-password 
  namespace: api
spec:
  vault:
    name: team1-aks-keyvault # name of key vault
    object:
      name: sql-password # name of the akv object
      type: secret # akv object type
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryogv7603.azurecr.io/tripinsights/poi:1.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: SQL_USER
          value: sqladminoGv7603
        - name: SQL_SERVER
          value: sqlserverogv7603.database.windows.net
        - name: SQL_PASSWORD
          value: "sql-password@azurekeyvault" 
        - name: SQL_DB
          value: mydrivingDB
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: api
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: poi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: poi
        image: registryogv7603.azurecr.io/tripinsights/trips:1.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: SQL_USER
          value: sqladminoGv7603
        - name: SQL_SERVER
          value: sqlserverogv7603.database.windows.net
        - name: SQL_PASSWORD
          value: "sql-password@azurekeyvault"
        - name: SQL_DB
          value: mydrivingDB
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: api
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: trips
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: poi
        image: registryogv7603.azurecr.io/tripinsights/userprofile:1.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: SQL_USER
          value: sqladminoGv7603
        - name: SQL_SERVER
          value: sqlserverogv7603.database.windows.net
        - name: SQL_PASSWORD
          value: "sql-password@azurekeyvault"
        - name: SQL_DB
          value: mydrivingDB
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  namespace: api
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: userprofile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: poi
        image: registryogv7603.azurecr.io/tripinsights/user-java:1.0
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 4Gi
        env:
        - name: SQL_USER
          value: sqladminoGv7603
        - name: SQL_SERVER
          value: sqlserverogv7603.database.windows.net
        - name: SQL_PASSWORD
          value: "sql-password@azurekeyvault"
        - name: SQL_DB
          value: mydrivingDB
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
  namespace: api
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: user-java
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: poi
        image: registryogv7603.azurecr.io/tripinsights/tripviewer:1.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile.api:80"
        - name: TRIPS_API_ENDPOINT
          value: "http://trips.api:80"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: web
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: tripviewer
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: web
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: tripviewer
          servicePort: 80
        path: /(.*)
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  namespace: api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: poi
          servicePort: 80
        path: /api/poi(/|$)(.*)
      - backend:
          serviceName: trips
          servicePort: 80
        path: /api/trips(/|$)(.*)
      - backend:
          serviceName: userprofile
          servicePort: 80
        path: /api/user(/|$)(.*)
      - backend:
          serviceName: user-java
          servicePort: 80
        path: /api/user-java(/|$)(.*)