apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryogv7603.azurecr.io/tripinsights/poi:1.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: SQL_USER
          value: sqladminoGv7603
        - name: SQL_SERVER
          value: sqlserverogv7603.database.windows.net
        - name: SQL_PASSWORD
          value: sA9ev6Sz0
        - name: SQL_DB
          value: mydrivingDB
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: poi
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: poi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: poi
        image: registryogv7603.azurecr.io/tripinsights/trips:1.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: SQL_USER
          value: sqladminoGv7603
        - name: SQL_SERVER
          value: sqlserverogv7603.database.windows.net
        - name: SQL_PASSWORD
          value: sA9ev6Sz0
        - name: SQL_DB
          value: mydrivingDB
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: trips
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: trips
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: poi
        image: registryogv7603.azurecr.io/tripinsights/userprofile:1.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: SQL_USER
          value: sqladminoGv7603
        - name: SQL_SERVER
          value: sqlserverogv7603.database.windows.net
        - name: SQL_PASSWORD
          value: sA9ev6Sz0
        - name: SQL_DB
          value: mydrivingDB
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: userprofile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: poi
        image: registryogv7603.azurecr.io/tripinsights/user-java:1.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: SQL_USER
          value: sqladminoGv7603
        - name: SQL_SERVER
          value: sqlserverogv7603.database.windows.net
        - name: SQL_PASSWORD
          value: sA9ev6Sz0
        - name: SQL_DB
          value: mydrivingDB
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: user-java
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: poi
        image: registryogv7603.azurecr.io/tripinsights/tripviewer:1.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: USERPROFILE_API_ENDPOINT
          value: "http://userprofile:80"
        - name: TRIPS_API_ENDPOINT
          value: "http://trips:80"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: tripviewer